FROM ft-rails:on-build

EXPOSE 3000
CMD [ "rails" , "s", "-b", "0.0.0.0", "-p", "3000"]

# Clone Rails
# Rrom https://bitbucket.org/railstutorial/sample_app_4th_ed/src/master/
# git clone --recurse-submodules https://bitbucket.org/railstutorial/sample_app_4th_ed.git app

# How to build it?
# docker build -t ex02 .

# How to run it?
# docker run -it --rm -p 3000:3000 ex02